# Generated by Django 4.0 on 2022-03-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
        migrations.AddField(
            model_name='category',
            name='category_code',
            field=models.CharField(default='ACC', max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(default=11, max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
