# Generated by Django 4.0 on 2022-05-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(related_name='options', to='store.Product'),
        ),
    ]
