# Generated by Django 4.0.4 on 2023-02-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail',
            field=models.DecimalField(blank=True, decimal_places=2, default=99.99, max_digits=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='certificates',
            field=models.FileField(upload_to='proofs/', verbose_name='Sales Tax ID'),
        ),
        
        
    ]
