# Generated by Django 4.0 on 2022-03-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0002_remove_category_code_category_category_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('vendor_code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='product_images/default.png', upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('deal_description', models.CharField(default='Discounted Price', max_length=255)),
                ('deal_price', models.DecimalField(blank=True, decimal_places=2, default=99.99, max_digits=4)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='auth.user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='store.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='store.vendor')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
