# Generated by Django 4.0 on 2022-03-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_vendor_alter_category_category_id_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deal_description',
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=1111, max_length=4),
            preserve_default=False,
        ),
    ]
