# Generated by Django 4.0 on 2022-03-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_category_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_code',
            new_name='vendor_id',
        ),
    ]
