# Generated by Django 4.0.4 on 2022-06-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_sku_alter_product_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
