# Generated by Django 4.0.4 on 2022-06-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_added_by_remove_product_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_code',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
    ]
