# Generated by Django 4.0 on 2022-03-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_vendor_code_vendor_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
