# Generated by Django 4.0 on 2022-03-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default='vendor_images/default.png', upload_to='vendor_images/'),
        ),
    ]
