# Generated by Django 4.0.4 on 2022-06-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_category_category_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SKU',
            new_name='sku',
        ),
    ]
