# Generated by Django 4.0.4 on 2022-06-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_sku_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail',
            field=models.DecimalField(blank=True, decimal_places=2, default=99.99, max_digits=6),
        ),
    ]
