# Generated by Django 4.0.4 on 2022-06-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_product_code_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
