# Generated by Django 4.0 on 2022-04-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_announcements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
    ]
