# Generated by Django 4.0.4 on 2022-06-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
