# Generated by Django 4.0 on 2022-04-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_announcements_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='vendor_images/default.png', upload_to='category_images/'),
        ),
    ]
