# Generated by Django 4.0.4 on 2022-06-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='3116 4th St'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='certificates',
            field=models.ImageField(upload_to='proofs/', verbose_name='Sales Tax ID'),
        ),
    ]
