# Generated by Django 4.0.4 on 2022-09-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_address_alter_userprofile_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='certificates',
            field=models.FileField(upload_to='proofs/', verbose_name='Sales Tax ID'),
        ),
    ]
