# Generated by Django 4.0.4 on 2022-11-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
