# Generated by Django 4.0.4 on 2022-11-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_userprofile_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='activate',
            new_name='is_active',
        ),
    ]
