# Generated by Django 4.0.4 on 2023-01-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_activate_userprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='certificates',
            field=models.FileField(blank=True, upload_to='proofs/', verbose_name='Sales Tax ID'),
        ),
    ]
