# Generated by Django 4.0.4 on 2023-01-21 22:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0022_customer_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='UserProfile',
        ),
    ]
